version: '3.1'

services:
  fastapi-app:
    restart: on-failure
    image: fastapi-img
    container_name: fastapi-container
    build: .
    command: python /app/main.py
    volumes: # sync updates between local folder and container
      - .:/app
    env_file:
      - .env
    environment:
       - DB_URL=mongodb://mongo:27017
    ports:
      - 8000:8000 # local:container
    depends_on: # start after mongo
      - "mongo"

  mongo:
    image: mongo:5.0.14
    container_name: mongo-db-container
    restart: always
    ports:
      - 37017:27017 #local:container
    volumes: # save db data
      - data:/data/db

volumes:
  data: